---
title: "Course Notes"
output: github_document
---

### Introduction to Data

First video talks about the dplyr package- will people know what this is? or what a package is?

Listed definition of "ordinal variable" in video doesn't distinguish it from a non-ordered categorical variable

First part of the course doesn't test on other questions, just code. You could use the multiple choice questions to ask what kinds of variables certain columns are. Alternatively, use the "storing the answer" technique to check this question like in the study identification slides.

Typo in "Discretize a different variable" slide, says `num_char_at` where it should say `num_char_cat`.

Clarity of the phrase "plot a vs. b"? This might just be my background, but every time I see this I map a to x and b to y, then it tells me I have to swap them.

Not all multiple choice questions have an explanation of the answer after the fact, namely the sampling information questions.

"Create a scatterplot" slide gives me an error message to use the `evals` dataset when it's being used. Can't find a way around it. When I run the given solution it continues to show "Incorrect submission".

Structure of vectors? This might be good to talk about with the "factor" data type.

Explanation of basic symbols like `<=` or `>=`, just for completeness' sake.

### Exploratory Data Analysis

`ggplot2` has a handful of verbs that you kind of just throw out there, would it be efficient to explain these a little more? Or just leave them to be explored?

Personally I really found it useful to learn all the `dplyr` syntax at once, but based on teaching code and stats techniques at the same time this might not make as much sense.

### Correlation and Regression

All three courses have used different conventions to label axes on graphs. `xlab`, `scale_x_continous`, and `labs` are all used. This could get confusing.

This one does a very good job of not being prescriptive. You really have to dive into the dataset and remember the code on your own.

### Foundations of Inference

First couple times through the sampling process were confusing, but going through it step-by-step on the "Step-by-step through the permutation" slide really helped.



### Other Notes

Andrew says prereqs will be Intro to R course and possibly dplyr or ggplot course

Comics comes from 538 package